Adding sample fabfile, travis ci and MIT free to use LICENSE
coderadi/flask-app pull request #9
Opened 2018-01-24 16:44 UTC by chowmean

2018-04-13 19:55 UTC, adityav-verma requested changes

2018-04-13 19:55 UTC, coderadi commented on .travis.yml
> +  - "pip install fab-polish"
The current version of `fab-polish` isn't python3 compatible.

2018-04-13 19:55 UTC, coderadi commented on .travis.yml
> +  - "2.7"
flask-app is built on python3.

2018-04-13 19:55 UTC, coderadi commented on fabfile.py
> +    """Requires nsp in package"""
Doc string and the function name don't actually match action they perform.

2018-05-02 10:38 UTC, coderadi commented
Forked FabPolish and added python3 support and upgraded the packages for coding standard checks.
Travis will require a paid account. Hence, closing this PR.

2018-05-02 10:38 UTC, closed without merging

2018-09-28 23:11 UTC, chowmean commented
> Travis will require a paid account. Hence, closing this PR.
Travis is free for open source projects. You can use this https://travis-ci.org/